/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sccc_incas;
import conexion_BD.Conexion_Consulta;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableColumnModel;
/**
 *
 * @author alexander
 */
public class Registros_MINED extends javax.swing.JFrame {
    
    Connection coon;
    Statement sent;
    DefaultTableModel model;
    
    /**
     * Creates new form ventana
     */
    public Registros_MINED() {
        initComponents();
        Conexion_Consulta.conectar();
        this.setLocationRelativeTo(null);
        
        colortransparent();
        PruebaJScrollPane();
        
        
        
    }
     public void colortransparent(){        
        Buscar.setBackground(new Color (0,0,0,0));
        Buscar_.setBackground(new Color (0,0,0,0));
        mostrar.setBackground(new Color (0,0,0,0));
        jTable1.setOpaque(false);
        
 
     
    }
    
  
      
      
      
       public void PruebaJScrollPane() { 
           jScrollPane1.getViewport().setBackground(new java.awt.Color(0,0,0,0));
    } 
       
 
 
public void Buscar (String texto){
    try {
    String [] titulos = {"idm", "nombre", "apellido", "hora_i", "hora_f", "fecha", "recurso_a", "actividad_a", "dui", "ob"};
    String filtro = ""+texto+"_%";
    String SQL = "SELECT * FROM mined WHERE fecha LIKE" + '"' + filtro + '"';
  
    System.out.println(SQL);
    model = new DefaultTableModel (null, titulos);
    sent = coon.prepareStatement(SQL);
    ResultSet rs = sent.executeQuery(SQL);
    String [] fila = new String [9];
    while (rs.next()){
        fila [0] =("idm");
        fila [1] =("nombre");
        fila [2] =("apellido");
        fila [3] =("hora_i");
        fila [4] =("hora_f");
        fila [5] =("fecha");
        fila [6] =("recurso_a");
        fila [7] =("actividad_a");
        fila [8] =("dui");
        fila [9] =("ob");
      
        model.addRow(fila);
        jTable1.setModel(model);
        
        rs.close();
        sent.close();
        
    }
    
    }
    catch (Exception e){
     System.err.println(""+e.getMessage());
    
    }
       
       
       
  
}
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Buscar_ = new javax.swing.JFormattedTextField();
        Buscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mostrar.setText("Mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 90, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 600, 230));

        Buscar_.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        Buscar_.setForeground(new java.awt.Color(255, 255, 255));
        try {
            Buscar_.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Buscar_.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Buscar_.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Buscar_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Buscar_KeyReleased(evt);
            }
        });
        getContentPane().add(Buscar_, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 455, 195, -1));

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 90, 30));

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_I_A.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID De MINED");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Hora Incial");
        modelo.addColumn("Hora Final");
        modelo.addColumn("Fecha");
        modelo.addColumn("Recurso A Utilizar");
        modelo.addColumn("Actividad A Utilizar");
        modelo.addColumn("N° De DUI");
        modelo.addColumn("Observaciones");
        ArrayList<Object[]> datos = new ArrayList<Object[]>();
        datos=Conexion_Consulta.llenar_tabla3();
        for(int i=0;i<datos.size();i++){
            modelo.addRow(datos.get(i));
        }
        jTable1.setModel(modelo);
    }//GEN-LAST:event_mostrarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String nombre = Buscar_.getText();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID De Alumno");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Hora Incial");
        modelo.addColumn("Hora Final");
        modelo.addColumn("Fecha");
        modelo.addColumn("Recurso A Utilizar");
        modelo.addColumn("Actividad A Utilizar");
        modelo.addColumn("N° De DUI");
        modelo.addColumn("Observaciones");
        ArrayList<Object[]> datos = new ArrayList<Object[]>();
        datos=Conexion_Consulta.buscar_tabla3(nombre);
        for(int i=0;i<datos.size();i++){
            modelo.addRow(datos.get(i));
        }
        jTable1.setModel(modelo);
    }//GEN-LAST:event_BuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Buscar_KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Buscar_KeyReleased
        // TODO add your handling code here:
        String buscar = Buscar.getText();
        Buscar(buscar);
    }//GEN-LAST:event_Buscar_KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registros_MINED.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registros_MINED.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registros_MINED.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registros_MINED.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registros_MINED().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JFormattedTextField Buscar_;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton mostrar;
    // End of variables declaration//GEN-END:variables
}
